import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './styles/variables.css'
import './styles/layout.css'
import './styles/buttons.css'
import './styles/modals.css'
import './styles/projects.css'
import './styles/console.css'
import './styles/ports.css'
import './styles/docker.css'
import './styles/servers.css'
import './styles/env-editor.css'
import './styles/docker-svc.css'
import './styles/window.css'
import './styles/update.css'

ReactDOM.createRoot(document.getElementById('root')).render(<App />)
