const fs = require('fs')
const path = require('path')
const crypto = require('crypto')

const SECRET_DESCRIPTIONS = {
  ANSIBLE_VAULT: 'Generated Ansible Vault password.',
  ANSIBLE_VAULET: 'Generated Ansible Vault password. This name keeps the workflow typo if it exists.',
  DOCKER_PASSWORD: 'Docker registry password or token. Fill manually.',
  DOCKER_USERNAME: 'Docker registry username. Fill manually.',
  INVENTORY_PROD: 'Generated Ansible inventory for the selected server.',
  KNOWN_HOSTS_PROD: 'Generated SSH known_hosts entry for the selected server.',
  KNOW_HOSTS_PROD: 'Generated SSH known_hosts entry. This name keeps the workflow typo if it exists.',
  SSH_PRIVATE_KEY: 'Generated private key for the deploy user.',
  SSH_PRIVATE_KEY_PROD: 'Generated private key for the deploy user.',
  STRAPI_URL: 'Application URL or Strapi URL. Fill manually if not generated by your workflow.',
  TELEGRAM_BOT_TOKEN: 'Telegram bot token for deploy notifications. Optional/manual.',
  TELEGRAM_CHAT_ID: 'Telegram chat id for deploy notifications. Optional/manual.'
}

function safeRead(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf-8')
  } catch {
    return ''
  }
}

function unique(values) {
  return [...new Set(values.filter(Boolean))]
}

function sanitizeSlug(value, fallback = 'app') {
  const slug = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
  return slug || fallback
}

function sanitizeLinuxUser(value, fallback = 'deploy') {
  const user = String(value || '')
    .toLowerCase()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 31)
  if (!user || !/^[a-z_]/.test(user)) return fallback
  return user
}

function listWorkflowFiles(projectPath) {
  const dir = path.join(projectPath, '.github', 'workflows')
  try {
    return fs.readdirSync(dir)
      .filter(name => /\.ya?ml$/i.test(name))
      .map(name => path.join(dir, name))
  } catch {
    return []
  }
}

function extractGithubRefs(content, kind) {
  const refs = []
  const re = new RegExp(`${kind}\\.([A-Z0-9_]+)`, 'g')
  let match
  while ((match = re.exec(content))) refs.push(match[1])
  return refs
}

function parseEnvExample(filePath) {
  return safeRead(filePath)
    .split('\n')
    .map(line => line.trim())
    .filter(line => line && !line.startsWith('#') && /^[A-Z0-9_]+=/.test(line))
    .map(line => line.split('=')[0])
}

function detectDeploySetup(projectPath) {
  const projectName = path.basename(projectPath || '') || 'project'
  const slug = sanitizeSlug(projectName)
  const deployDir = path.join(projectPath, 'deploy')
  const deploymentDir = path.join(projectPath, 'deployment')
  const hasDeployDir = fs.existsSync(deployDir)
  const hasDeploymentDir = fs.existsSync(deploymentDir)
  const deployFiles = hasDeployDir ? safeList(deployDir) : []
  const deploymentFiles = hasDeploymentDir ? safeList(deploymentDir) : []
  const autodeployScript = deployFiles.find(name => /autodeploy.*\.sh$|.*-autodeploy\.sh$/i.test(name)) || ''
  const workflowFiles = listWorkflowFiles(projectPath)
  const workflowRefs = workflowFiles.map(filePath => {
    const content = safeRead(filePath)
    return {
      file: path.relative(projectPath, filePath),
      secrets: extractGithubRefs(content, 'secrets'),
      variables: extractGithubRefs(content, 'vars')
    }
  })
  const secrets = unique(workflowRefs.flatMap(item => item.secrets))
  const variables = unique(workflowRefs.flatMap(item => item.variables))
  const mode = autodeployScript ? 'private-vpn' : 'github-direct'
  const envExamplePath = path.join(deployDir, 'server.env.example')

  return {
    projectName,
    slug,
    mode,
    deployUser: sanitizeLinuxUser(`deploy-${slug}`, 'deploy'),
    remoteBase: `/opt/${slug}`,
    hasDeployDir,
    hasDeploymentDir,
    deployDir: hasDeployDir ? deployDir : null,
    deploymentDir: hasDeploymentDir ? deploymentDir : null,
    deployFiles,
    deploymentFiles,
    autodeployScript,
    workflowFiles: workflowRefs,
    secrets,
    variables,
    serverEnvKeys: parseEnvExample(envExamplePath),
    recommendations: buildRecommendations({ mode, secrets, variables, autodeployScript, hasDeploymentDir })
  }
}

function safeList(dir) {
  try {
    return fs.readdirSync(dir).sort((a, b) => a.localeCompare(b))
  } catch {
    return []
  }
}

function buildRecommendations({ mode, secrets, variables, autodeployScript, hasDeploymentDir }) {
  const items = []
  if (mode === 'private-vpn') {
    items.push('Private/VPN profile detected: install server-side deploy assets and cron on the selected server.')
    if (autodeployScript) items.push(`Autodeploy script detected: ${autodeployScript}.`)
  } else if (hasDeploymentDir) {
    items.push('GitHub direct profile detected: workflow can run Ansible/deploy files from the repository.')
  }
  if (secrets.length > 0) items.push(`Workflow secrets detected: ${secrets.join(', ')}.`)
  if (variables.length > 0) items.push(`Workflow variables detected: ${variables.join(', ')}.`)
  return items
}

function buildInventory({ host, port, deployUser }) {
  const safeHost = String(host || '').trim()
  const safePort = parseInt(port, 10) || 22
  const safeUser = sanitizeLinuxUser(deployUser, 'deploy')
  return `[prod]\n${safeHost} ansible_host=${safeHost} ansible_user=${safeUser} ansible_port=${safePort}\n`
}

function generateVaultPassword() {
  return crypto.randomBytes(24).toString('base64url')
}

function buildSecretBundle({ detectedSecrets = [], mode, privateKey, knownHosts, inventory, vaultPassword }) {
  const knownHostsName = detectedSecrets.includes('KNOW_HOSTS_PROD') ? 'KNOW_HOSTS_PROD' : 'KNOWN_HOSTS_PROD'
  const vaultName = detectedSecrets.includes('ANSIBLE_VAULET') ? 'ANSIBLE_VAULET' : 'ANSIBLE_VAULT'
  const recommended = mode === 'private-vpn'
    ? ['SSH_PRIVATE_KEY_PROD', 'INVENTORY_PROD', knownHostsName, vaultName]
    : ['SSH_PRIVATE_KEY_PROD', 'INVENTORY_PROD', knownHostsName]
  const names = unique([...detectedSecrets, ...recommended])
  return names.map(name => {
    const value = secretValue(name, { privateKey, knownHosts, inventory, vaultPassword })
    return {
      name,
      value,
      generated: value !== '',
      detected: detectedSecrets.includes(name),
      description: SECRET_DESCRIPTIONS[name] || 'Project-specific secret. Fill manually.'
    }
  })
}

function secretValue(name, generated) {
  if (/^SSH_PRIVATE_KEY/.test(name)) return generated.privateKey || ''
  if (name === 'INVENTORY_PROD') return generated.inventory || ''
  if (name === 'KNOWN_HOSTS_PROD' || name === 'KNOW_HOSTS_PROD') return generated.knownHosts || ''
  if (name === 'ANSIBLE_VAULT' || name === 'ANSIBLE_VAULET') return generated.vaultPassword || ''
  return ''
}

module.exports = {
  detectDeploySetup,
  buildInventory,
  buildSecretBundle,
  generateVaultPassword,
  sanitizeSlug,
  sanitizeLinuxUser
}
